// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/k8s/v1alpha1.WeatherReport":       schema_pkg_apis_k8s_v1alpha1_WeatherReport(ref),
		"./pkg/apis/k8s/v1alpha1.WeatherReportSpec":   schema_pkg_apis_k8s_v1alpha1_WeatherReportSpec(ref),
		"./pkg/apis/k8s/v1alpha1.WeatherReportStatus": schema_pkg_apis_k8s_v1alpha1_WeatherReportStatus(ref),
	}
}

func schema_pkg_apis_k8s_v1alpha1_WeatherReport(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WeatherReport is the Schema for the weatherreports API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/k8s/v1alpha1.WeatherReportSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/k8s/v1alpha1.WeatherReportStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/k8s/v1alpha1.WeatherReportSpec", "./pkg/apis/k8s/v1alpha1.WeatherReportStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_k8s_v1alpha1_WeatherReportSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WeatherReportSpec defines the desired state of WeatherReport",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_k8s_v1alpha1_WeatherReportStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WeatherReportStatus defines the observed state of WeatherReport",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
